from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
REPORTS = ROOT / "reports"


def load(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def records(payload: dict) -> list[dict]:
    rows = payload.get("records")
    return rows if isinstance(rows, list) else []


def to_float(value: object) -> float | None:
    try:
        if value is None:
            return None
        return float(value)
    except (TypeError, ValueError):
        return None


def row_usd_value(row: dict, eth_fallback_price: float = 2800.0) -> float | None:
    # Prefer row-level valuation generated by the pipeline.
    usd = to_float(row.get("usd_value_at_execution"))
    if usd is not None:
        return usd

    symbol = str(row.get("asset") or row.get("asset_symbol") or "").upper()
    amount = to_float(row.get("amount")) or 0.0
    if symbol == "USDC":
        return amount
    if symbol == "ETH":
        return amount * eth_fallback_price
    return None


def build_tags_index(tags: list[dict]) -> dict[str, dict]:
    index: dict[str, dict] = {}
    for row in tags:
        archive_id = row.get("archive_id")
        if archive_id:
            index[str(archive_id)] = row
    return index


def row_category(row: dict, tags_index: dict[str, dict]) -> str | None:
    for key in ("semantic_category", "category", "primary_category"):
        value = row.get(key)
        if has_value(value):
            return str(value)

    tag = tags_index.get(str(row.get("archive_id") or ""))
    if not tag:
        return None
    for key in ("semantic_category", "primary_category"):
        value = tag.get(key)
        if has_value(value):
            return str(value)
    return None


def row_sport(row: dict, tags_index: dict[str, dict]) -> str | None:
    if has_value(row.get("sport")):
        return str(row.get("sport"))
    tag = tags_index.get(str(row.get("archive_id") or ""))
    if tag and has_value(tag.get("sport")):
        return str(tag.get("sport"))
    return None


def has_value(value: object) -> bool:
    if value is None:
        return False
    if isinstance(value, str):
        return value.strip() != ""
    if isinstance(value, (list, dict)):
        return len(value) > 0
    return True


def write_report(lines: list[str]) -> None:
    REPORTS.mkdir(parents=True, exist_ok=True)
    out = REPORTS / "data_gaps.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")


def check_sankey_completeness(spend: list[dict], dao_metrics: dict, tags_index: dict[str, dict]) -> str:
    priced_rows = [row_usd_value(row) for row in spend]
    total_in_ledger = sum(value for value in priced_rows if value is not None)
    categorized = sum(
        (row_usd_value(row) or 0.0)
        for row in spend
        if (row_category(row, tags_index) or "").strip().lower() not in {"", "uncategorized", "other"}
    )
    unpriced_rows = sum(1 for value in priced_rows if value is None)
    sankey_total = (dao_metrics.get("sankey_total_k", 0) or 0) * 1000
    coverage = round((categorized / total_in_ledger) * 100) if total_in_ledger else 0

    return f"""
SANKEY COMPLETENESS
--------------------------------
Total in spend_ledger:    ${total_in_ledger:>10,.0f}
Categorized (in Sankey):  ${categorized:>10,.0f}
Sankey total (from JSON): ${sankey_total:>10,.0f}
Coverage:                  {coverage}%
Drift (ledger vs sankey):  ${abs(categorized - sankey_total):>10,.0f}
Unpriced ledger rows:      {unpriced_rows}
"""


def main() -> None:
    spend = records(load(DATA / "spend_ledger.json"))
    tags = records(load(DATA / "proposal_tags.json"))
    tags_index = build_tags_index(tags)
    members = records(load(DATA / "members.json"))
    props = records(load(DATA / "proposals_archive.json"))
    dao_metrics = load(DATA / "dao_metrics.json")

    spend_no_project = sum(1 for row in spend if not has_value(row.get("project_id")))
    spend_no_category = sum(
        1
        for row in spend
        if not has_value(row_category(row, tags_index))
    )
    spend_no_sport = sum(1 for row in spend if not has_value(row_sport(row, tags_index)))
    spend_no_recipient_name = sum(
        1 for row in spend if not has_value(row.get("recipient_name")) and not has_value(row.get("recipient_display_name"))
    )

    tags_no_semantic = sum(1 for row in tags if not has_value(row.get("semantic_category")))
    tags_no_sport = sum(1 for row in tags if not has_value(row.get("sport")))
    tags_no_breakdown = sum(1 for row in tags if not has_value(row.get("capital_breakdown")))
    tags_no_confidence = sum(
        1 for row in tags if row.get("semantic_confidence") is None and row.get("confidence") is None
    )

    members_athlete = [
        row
        for row in members
        if "athlete" in [str(v).lower() for v in row.get("tags", [])]
        or "athlete" in [str(v).lower() for v in row.get("domains", [])]
    ]
    members_no_sport = sum(1 for row in members_athlete if not has_value(row.get("sport")))
    members_no_totals = sum(
        1
        for row in members
        if row.get("total_received_usdc") is None and row.get("total_received_eth") is None
    )

    proposals_uncategorized = sum(
        1
        for row in props
        if not has_value(row.get("category"))
        and not has_value(row.get("primary_category"))
        and not has_value(row.get("semantic_category"))
    )

    gaps = {
        "spend_no_project": spend_no_project,
        "spend_no_category": spend_no_category,
        "spend_no_sport": spend_no_sport,
        "spend_no_recipient_name": spend_no_recipient_name,
        "tags_no_semantic": tags_no_semantic,
        "tags_no_sport": tags_no_sport,
        "tags_no_capital_breakdown": tags_no_breakdown,
        "tags_no_confidence": tags_no_confidence,
        "members_no_sport": members_no_sport,
        "members_no_totals": members_no_totals,
        "proposals_uncategorized": proposals_uncategorized,
    }

    lines = ["# Data Gaps Report", "", "| Field | Missing |", "|---|---|"]
    lines.extend(f"| {k} | {v} |" for k, v in gaps.items())

    sankey_report = check_sankey_completeness(spend, dao_metrics, tags_index)
    lines.extend(["", "## Sankey Completeness", "", "```text", sankey_report.strip("\n"), "```"])

    write_report(lines)
    print("\n".join(lines))
    print(sankey_report)


if __name__ == "__main__":
    main()
